// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AccessReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from AccessReq.proto</summary>
  public static partial class AccessReqReflection {

    #region Descriptor
    /// <summary>File descriptor for AccessReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccessReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9BY2Nlc3NSZXEucHJvdG8aEkh5YmVQcm92aWRlci5wcm90bxoPSHliZUxv",
            "Z09TLnByb3RvIt8CCglBY2Nlc3NSZXESDQoFdG9rZW4YASABKAkSDQoFaW1f",
            "aWQYAiABKAkSEQoJbmlja19uYW1lGAMgASgJEg8KB2NvdW50cnkYBCABKAkS",
            "EQoJY2xpZW50X2lwGAUgASgJEiIKCWF1dGhfdHlwZRgGIAEoDjIPLkh5YmVQ",
            "cm92aWRlci5UEhcKD2F1dGhfaWRfYnlfdHlwZRgHIAEoCRIPCgdhdXRoX2lk",
            "GAggASgJEh0KB29zX3R5cGUYCSABKA4yDC5IeWJlTG9nT1MuVBIOCgZvc192",
            "ZXIYCiABKAkSEAoIbGFuZ3VhZ2UYCyABKAkSEgoKZGV2aWNlX21vZBgMIAEo",
            "CRIaChJleHRlcm5hbF9kZXZpY2VfaWQYDSABKAkSEgoKYnVuZGxlX3ZlchgO",
            "IAEoCRISCgpjbGllbnRfdmVyGA8gASgJEhYKDmFkdmVydGlzaW5nX2lkGBAg",
            "ASgJQgWqAgJPemIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.HybeProviderReflection.Descriptor, global::Oz.HybeLogOSReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.AccessReq), global::Oz.AccessReq.Parser, new[]{ "Token", "ImId", "NickName", "Country", "ClientIp", "AuthType", "AuthIdByType", "AuthId", "OsType", "OsVer", "Language", "DeviceMod", "ExternalDeviceId", "BundleVer", "ClientVer", "AdvertisingId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AccessReq : pb::IMessage<AccessReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccessReq> _parser = new pb::MessageParser<AccessReq>(() => new AccessReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccessReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.AccessReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessReq(AccessReq other) : this() {
      token_ = other.token_;
      imId_ = other.imId_;
      nickName_ = other.nickName_;
      country_ = other.country_;
      clientIp_ = other.clientIp_;
      authType_ = other.authType_;
      authIdByType_ = other.authIdByType_;
      authId_ = other.authId_;
      osType_ = other.osType_;
      osVer_ = other.osVer_;
      language_ = other.language_;
      deviceMod_ = other.deviceMod_;
      externalDeviceId_ = other.externalDeviceId_;
      bundleVer_ = other.bundleVer_;
      clientVer_ = other.clientVer_;
      advertisingId_ = other.advertisingId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccessReq Clone() {
      return new AccessReq(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "im_id" field.</summary>
    public const int ImIdFieldNumber = 2;
    private string imId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImId {
      get { return imId_; }
      set {
        imId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nick_name" field.</summary>
    public const int NickNameFieldNumber = 3;
    private string nickName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NickName {
      get { return nickName_; }
      set {
        nickName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 4;
    private string country_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_ip" field.</summary>
    public const int ClientIpFieldNumber = 5;
    private string clientIp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientIp {
      get { return clientIp_; }
      set {
        clientIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auth_type" field.</summary>
    public const int AuthTypeFieldNumber = 6;
    private global::Oz.HybeProvider.Types.T authType_ = global::Oz.HybeProvider.Types.T.Guest;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.HybeProvider.Types.T AuthType {
      get { return authType_; }
      set {
        authType_ = value;
      }
    }

    /// <summary>Field number for the "auth_id_by_type" field.</summary>
    public const int AuthIdByTypeFieldNumber = 7;
    private string authIdByType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthIdByType {
      get { return authIdByType_; }
      set {
        authIdByType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auth_id" field.</summary>
    public const int AuthIdFieldNumber = 8;
    private string authId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthId {
      get { return authId_; }
      set {
        authId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "os_type" field.</summary>
    public const int OsTypeFieldNumber = 9;
    private global::Oz.HybeLogOS.Types.T osType_ = global::Oz.HybeLogOS.Types.T.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.HybeLogOS.Types.T OsType {
      get { return osType_; }
      set {
        osType_ = value;
      }
    }

    /// <summary>Field number for the "os_ver" field.</summary>
    public const int OsVerFieldNumber = 10;
    private string osVer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OsVer {
      get { return osVer_; }
      set {
        osVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "language" field.</summary>
    public const int LanguageFieldNumber = 11;
    private string language_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Language {
      get { return language_; }
      set {
        language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_mod" field.</summary>
    public const int DeviceModFieldNumber = 12;
    private string deviceMod_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceMod {
      get { return deviceMod_; }
      set {
        deviceMod_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "external_device_id" field.</summary>
    public const int ExternalDeviceIdFieldNumber = 13;
    private string externalDeviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExternalDeviceId {
      get { return externalDeviceId_; }
      set {
        externalDeviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bundle_ver" field.</summary>
    public const int BundleVerFieldNumber = 14;
    private string bundleVer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BundleVer {
      get { return bundleVer_; }
      set {
        bundleVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_ver" field.</summary>
    public const int ClientVerFieldNumber = 15;
    private string clientVer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientVer {
      get { return clientVer_; }
      set {
        clientVer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "advertising_id" field.</summary>
    public const int AdvertisingIdFieldNumber = 16;
    private string advertisingId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AdvertisingId {
      get { return advertisingId_; }
      set {
        advertisingId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccessReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccessReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      if (ImId != other.ImId) return false;
      if (NickName != other.NickName) return false;
      if (Country != other.Country) return false;
      if (ClientIp != other.ClientIp) return false;
      if (AuthType != other.AuthType) return false;
      if (AuthIdByType != other.AuthIdByType) return false;
      if (AuthId != other.AuthId) return false;
      if (OsType != other.OsType) return false;
      if (OsVer != other.OsVer) return false;
      if (Language != other.Language) return false;
      if (DeviceMod != other.DeviceMod) return false;
      if (ExternalDeviceId != other.ExternalDeviceId) return false;
      if (BundleVer != other.BundleVer) return false;
      if (ClientVer != other.ClientVer) return false;
      if (AdvertisingId != other.AdvertisingId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (ImId.Length != 0) hash ^= ImId.GetHashCode();
      if (NickName.Length != 0) hash ^= NickName.GetHashCode();
      if (Country.Length != 0) hash ^= Country.GetHashCode();
      if (ClientIp.Length != 0) hash ^= ClientIp.GetHashCode();
      if (AuthType != global::Oz.HybeProvider.Types.T.Guest) hash ^= AuthType.GetHashCode();
      if (AuthIdByType.Length != 0) hash ^= AuthIdByType.GetHashCode();
      if (AuthId.Length != 0) hash ^= AuthId.GetHashCode();
      if (OsType != global::Oz.HybeLogOS.Types.T.None) hash ^= OsType.GetHashCode();
      if (OsVer.Length != 0) hash ^= OsVer.GetHashCode();
      if (Language.Length != 0) hash ^= Language.GetHashCode();
      if (DeviceMod.Length != 0) hash ^= DeviceMod.GetHashCode();
      if (ExternalDeviceId.Length != 0) hash ^= ExternalDeviceId.GetHashCode();
      if (BundleVer.Length != 0) hash ^= BundleVer.GetHashCode();
      if (ClientVer.Length != 0) hash ^= ClientVer.GetHashCode();
      if (AdvertisingId.Length != 0) hash ^= AdvertisingId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (ImId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ImId);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NickName);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Country);
      }
      if (ClientIp.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientIp);
      }
      if (AuthType != global::Oz.HybeProvider.Types.T.Guest) {
        output.WriteRawTag(48);
        output.WriteEnum((int) AuthType);
      }
      if (AuthIdByType.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(AuthIdByType);
      }
      if (AuthId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(AuthId);
      }
      if (OsType != global::Oz.HybeLogOS.Types.T.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) OsType);
      }
      if (OsVer.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(OsVer);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Language);
      }
      if (DeviceMod.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DeviceMod);
      }
      if (ExternalDeviceId.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(ExternalDeviceId);
      }
      if (BundleVer.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(BundleVer);
      }
      if (ClientVer.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(ClientVer);
      }
      if (AdvertisingId.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(AdvertisingId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (ImId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ImId);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NickName);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Country);
      }
      if (ClientIp.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientIp);
      }
      if (AuthType != global::Oz.HybeProvider.Types.T.Guest) {
        output.WriteRawTag(48);
        output.WriteEnum((int) AuthType);
      }
      if (AuthIdByType.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(AuthIdByType);
      }
      if (AuthId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(AuthId);
      }
      if (OsType != global::Oz.HybeLogOS.Types.T.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) OsType);
      }
      if (OsVer.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(OsVer);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Language);
      }
      if (DeviceMod.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DeviceMod);
      }
      if (ExternalDeviceId.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(ExternalDeviceId);
      }
      if (BundleVer.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(BundleVer);
      }
      if (ClientVer.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(ClientVer);
      }
      if (AdvertisingId.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(AdvertisingId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (ImId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImId);
      }
      if (NickName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickName);
      }
      if (Country.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (ClientIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientIp);
      }
      if (AuthType != global::Oz.HybeProvider.Types.T.Guest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AuthType);
      }
      if (AuthIdByType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthIdByType);
      }
      if (AuthId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthId);
      }
      if (OsType != global::Oz.HybeLogOS.Types.T.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OsType);
      }
      if (OsVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OsVer);
      }
      if (Language.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Language);
      }
      if (DeviceMod.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceMod);
      }
      if (ExternalDeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExternalDeviceId);
      }
      if (BundleVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BundleVer);
      }
      if (ClientVer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientVer);
      }
      if (AdvertisingId.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AdvertisingId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccessReq other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.ImId.Length != 0) {
        ImId = other.ImId;
      }
      if (other.NickName.Length != 0) {
        NickName = other.NickName;
      }
      if (other.Country.Length != 0) {
        Country = other.Country;
      }
      if (other.ClientIp.Length != 0) {
        ClientIp = other.ClientIp;
      }
      if (other.AuthType != global::Oz.HybeProvider.Types.T.Guest) {
        AuthType = other.AuthType;
      }
      if (other.AuthIdByType.Length != 0) {
        AuthIdByType = other.AuthIdByType;
      }
      if (other.AuthId.Length != 0) {
        AuthId = other.AuthId;
      }
      if (other.OsType != global::Oz.HybeLogOS.Types.T.None) {
        OsType = other.OsType;
      }
      if (other.OsVer.Length != 0) {
        OsVer = other.OsVer;
      }
      if (other.Language.Length != 0) {
        Language = other.Language;
      }
      if (other.DeviceMod.Length != 0) {
        DeviceMod = other.DeviceMod;
      }
      if (other.ExternalDeviceId.Length != 0) {
        ExternalDeviceId = other.ExternalDeviceId;
      }
      if (other.BundleVer.Length != 0) {
        BundleVer = other.BundleVer;
      }
      if (other.ClientVer.Length != 0) {
        ClientVer = other.ClientVer;
      }
      if (other.AdvertisingId.Length != 0) {
        AdvertisingId = other.AdvertisingId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 18: {
            ImId = input.ReadString();
            break;
          }
          case 26: {
            NickName = input.ReadString();
            break;
          }
          case 34: {
            Country = input.ReadString();
            break;
          }
          case 42: {
            ClientIp = input.ReadString();
            break;
          }
          case 48: {
            AuthType = (global::Oz.HybeProvider.Types.T) input.ReadEnum();
            break;
          }
          case 58: {
            AuthIdByType = input.ReadString();
            break;
          }
          case 66: {
            AuthId = input.ReadString();
            break;
          }
          case 72: {
            OsType = (global::Oz.HybeLogOS.Types.T) input.ReadEnum();
            break;
          }
          case 82: {
            OsVer = input.ReadString();
            break;
          }
          case 90: {
            Language = input.ReadString();
            break;
          }
          case 98: {
            DeviceMod = input.ReadString();
            break;
          }
          case 106: {
            ExternalDeviceId = input.ReadString();
            break;
          }
          case 114: {
            BundleVer = input.ReadString();
            break;
          }
          case 122: {
            ClientVer = input.ReadString();
            break;
          }
          case 130: {
            AdvertisingId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 18: {
            ImId = input.ReadString();
            break;
          }
          case 26: {
            NickName = input.ReadString();
            break;
          }
          case 34: {
            Country = input.ReadString();
            break;
          }
          case 42: {
            ClientIp = input.ReadString();
            break;
          }
          case 48: {
            AuthType = (global::Oz.HybeProvider.Types.T) input.ReadEnum();
            break;
          }
          case 58: {
            AuthIdByType = input.ReadString();
            break;
          }
          case 66: {
            AuthId = input.ReadString();
            break;
          }
          case 72: {
            OsType = (global::Oz.HybeLogOS.Types.T) input.ReadEnum();
            break;
          }
          case 82: {
            OsVer = input.ReadString();
            break;
          }
          case 90: {
            Language = input.ReadString();
            break;
          }
          case 98: {
            DeviceMod = input.ReadString();
            break;
          }
          case 106: {
            ExternalDeviceId = input.ReadString();
            break;
          }
          case 114: {
            BundleVer = input.ReadString();
            break;
          }
          case 122: {
            ClientVer = input.ReadString();
            break;
          }
          case 130: {
            AdvertisingId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
