// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: BattleModePartyType.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Oz
{

    [global::ProtoBuf.ProtoContract()]
    public enum BattleModePartyType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_None")]
        BattleModePartyTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_StoryModeParty")]
        BattleModePartyTypeStoryModeParty = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_ArenaModeAttackParty")]
        BattleModePartyTypeArenaModeAttackParty = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_ArenaModeDefenceParty")]
        BattleModePartyTypeArenaModeDefenceParty = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_AdventureModeParty")]
        BattleModePartyTypeAdventureModeParty = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_DungeonModeParty")]
        BattleModePartyTypeDungeonModeParty = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_RuinsModeParty")]
        BattleModePartyTypeRuinsModeParty = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_TotalWarModeParty")]
        BattleModePartyTypeTotalWarModeParty = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModePartyType_MAX")]
        BattleModePartyTypeMAX = 8,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
