// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: BattleModeType.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Oz
{

    [global::ProtoBuf.ProtoContract()]
    public enum BattleModeType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_None")]
        BattleModeTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_TutorialMode")]
        BattleModeTypeTutorialMode = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_StoryMode")]
        BattleModeTypeStoryMode = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_ArenaMode")]
        BattleModeTypeArenaMode = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_AdventureMode")]
        BattleModeTypeAdventureMode = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_DungeonMode")]
        BattleModeTypeDungeonMode = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_RuinsMode")]
        BattleModeTypeRuinsMode = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_TotalWarMode")]
        BattleModeTypeTotalWarMode = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"BattleModeType_MAX")]
        BattleModeTypeMAX = 8,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
