// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MailGetReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from MailGetReq.proto</summary>
  public static partial class MailGetReqReflection {

    #region Descriptor
    /// <summary>File descriptor for MailGetReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MailGetReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBNYWlsR2V0UmVxLnByb3RvGhJNYWlsU29ydFR5cGUucHJvdG8idAoKTWFp",
            "bEdldFJlcRITCgtzdGFydF9pbmRleBgBIAEoBRIUCgx1aV9vcGVuX3RpbWUY",
            "AiABKAMSIgoJc29ydF90eXBlGAMgASgOMg8uTWFpbFNvcnRUeXBlLlQSFwoP",
            "aXNfc29ydF9ieV9kZXNjGAQgASgIQgWqAgJPemIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.MailSortTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.MailGetReq), global::Oz.MailGetReq.Parser, new[]{ "StartIndex", "UiOpenTime", "SortType", "IsSortByDesc" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MailGetReq : pb::IMessage<MailGetReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MailGetReq> _parser = new pb::MessageParser<MailGetReq>(() => new MailGetReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MailGetReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.MailGetReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MailGetReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MailGetReq(MailGetReq other) : this() {
      startIndex_ = other.startIndex_;
      uiOpenTime_ = other.uiOpenTime_;
      sortType_ = other.sortType_;
      isSortByDesc_ = other.isSortByDesc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MailGetReq Clone() {
      return new MailGetReq(this);
    }

    /// <summary>Field number for the "start_index" field.</summary>
    public const int StartIndexFieldNumber = 1;
    private int startIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StartIndex {
      get { return startIndex_; }
      set {
        startIndex_ = value;
      }
    }

    /// <summary>Field number for the "ui_open_time" field.</summary>
    public const int UiOpenTimeFieldNumber = 2;
    private long uiOpenTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UiOpenTime {
      get { return uiOpenTime_; }
      set {
        uiOpenTime_ = value;
      }
    }

    /// <summary>Field number for the "sort_type" field.</summary>
    public const int SortTypeFieldNumber = 3;
    private global::Oz.MailSortType.Types.T sortType_ = global::Oz.MailSortType.Types.T.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.MailSortType.Types.T SortType {
      get { return sortType_; }
      set {
        sortType_ = value;
      }
    }

    /// <summary>Field number for the "is_sort_by_desc" field.</summary>
    public const int IsSortByDescFieldNumber = 4;
    private bool isSortByDesc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSortByDesc {
      get { return isSortByDesc_; }
      set {
        isSortByDesc_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MailGetReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MailGetReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartIndex != other.StartIndex) return false;
      if (UiOpenTime != other.UiOpenTime) return false;
      if (SortType != other.SortType) return false;
      if (IsSortByDesc != other.IsSortByDesc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StartIndex != 0) hash ^= StartIndex.GetHashCode();
      if (UiOpenTime != 0L) hash ^= UiOpenTime.GetHashCode();
      if (SortType != global::Oz.MailSortType.Types.T.None) hash ^= SortType.GetHashCode();
      if (IsSortByDesc != false) hash ^= IsSortByDesc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StartIndex);
      }
      if (UiOpenTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UiOpenTime);
      }
      if (SortType != global::Oz.MailSortType.Types.T.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) SortType);
      }
      if (IsSortByDesc != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsSortByDesc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StartIndex);
      }
      if (UiOpenTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UiOpenTime);
      }
      if (SortType != global::Oz.MailSortType.Types.T.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) SortType);
      }
      if (IsSortByDesc != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsSortByDesc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StartIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartIndex);
      }
      if (UiOpenTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UiOpenTime);
      }
      if (SortType != global::Oz.MailSortType.Types.T.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SortType);
      }
      if (IsSortByDesc != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MailGetReq other) {
      if (other == null) {
        return;
      }
      if (other.StartIndex != 0) {
        StartIndex = other.StartIndex;
      }
      if (other.UiOpenTime != 0L) {
        UiOpenTime = other.UiOpenTime;
      }
      if (other.SortType != global::Oz.MailSortType.Types.T.None) {
        SortType = other.SortType;
      }
      if (other.IsSortByDesc != false) {
        IsSortByDesc = other.IsSortByDesc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartIndex = input.ReadInt32();
            break;
          }
          case 16: {
            UiOpenTime = input.ReadInt64();
            break;
          }
          case 24: {
            SortType = (global::Oz.MailSortType.Types.T) input.ReadEnum();
            break;
          }
          case 32: {
            IsSortByDesc = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartIndex = input.ReadInt32();
            break;
          }
          case 16: {
            UiOpenTime = input.ReadInt64();
            break;
          }
          case 24: {
            SortType = (global::Oz.MailSortType.Types.T) input.ReadEnum();
            break;
          }
          case 32: {
            IsSortByDesc = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
