// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MissionGetReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from MissionGetReq.proto</summary>
  public static partial class MissionGetReqReflection {

    #region Descriptor
    /// <summary>File descriptor for MissionGetReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MissionGetReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNNaXNzaW9uR2V0UmVxLnByb3RvGhZNaXNzaW9uR3JvdXBUeXBlLnByb3Rv",
            "GhZHdWlkZU1pc3Npb25UeXBlLnByb3RvIm0KDU1pc3Npb25HZXRSZXESLQoS",
            "bWlzc2lvbl9ncm91cF90eXBlGAEgASgOMhEuTWlzc2lvbkdyb3VwVHlwZRIt",
            "ChJndWlkZV9taXNzaW9uX3R5cGUYAiABKA4yES5HdWlkZU1pc3Npb25UeXBl",
            "QgWqAgJPemIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.MissionGroupTypeReflection.Descriptor, global::Oz.GuideMissionTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.MissionGetReq), global::Oz.MissionGetReq.Parser, new[]{ "MissionGroupType", "GuideMissionType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MissionGetReq : pb::IMessage<MissionGetReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MissionGetReq> _parser = new pb::MessageParser<MissionGetReq>(() => new MissionGetReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MissionGetReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.MissionGetReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissionGetReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissionGetReq(MissionGetReq other) : this() {
      missionGroupType_ = other.missionGroupType_;
      guideMissionType_ = other.guideMissionType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MissionGetReq Clone() {
      return new MissionGetReq(this);
    }

    /// <summary>Field number for the "mission_group_type" field.</summary>
    public const int MissionGroupTypeFieldNumber = 1;
    private global::Oz.MissionGroupType missionGroupType_ = global::Oz.MissionGroupType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.MissionGroupType MissionGroupType {
      get { return missionGroupType_; }
      set {
        missionGroupType_ = value;
      }
    }

    /// <summary>Field number for the "guide_mission_type" field.</summary>
    public const int GuideMissionTypeFieldNumber = 2;
    private global::Oz.GuideMissionType guideMissionType_ = global::Oz.GuideMissionType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.GuideMissionType GuideMissionType {
      get { return guideMissionType_; }
      set {
        guideMissionType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MissionGetReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MissionGetReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MissionGroupType != other.MissionGroupType) return false;
      if (GuideMissionType != other.GuideMissionType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MissionGroupType != global::Oz.MissionGroupType.None) hash ^= MissionGroupType.GetHashCode();
      if (GuideMissionType != global::Oz.GuideMissionType.None) hash ^= GuideMissionType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MissionGroupType != global::Oz.MissionGroupType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MissionGroupType);
      }
      if (GuideMissionType != global::Oz.GuideMissionType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GuideMissionType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MissionGroupType != global::Oz.MissionGroupType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MissionGroupType);
      }
      if (GuideMissionType != global::Oz.GuideMissionType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GuideMissionType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MissionGroupType != global::Oz.MissionGroupType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MissionGroupType);
      }
      if (GuideMissionType != global::Oz.GuideMissionType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GuideMissionType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MissionGetReq other) {
      if (other == null) {
        return;
      }
      if (other.MissionGroupType != global::Oz.MissionGroupType.None) {
        MissionGroupType = other.MissionGroupType;
      }
      if (other.GuideMissionType != global::Oz.GuideMissionType.None) {
        GuideMissionType = other.GuideMissionType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MissionGroupType = (global::Oz.MissionGroupType) input.ReadEnum();
            break;
          }
          case 16: {
            GuideMissionType = (global::Oz.GuideMissionType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MissionGroupType = (global::Oz.MissionGroupType) input.ReadEnum();
            break;
          }
          case 16: {
            GuideMissionType = (global::Oz.GuideMissionType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
