// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OZAdventure.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from OZAdventure.proto</summary>
  public static partial class OZAdventureReflection {

    #region Descriptor
    /// <summary>File descriptor for OZAdventure.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OZAdventureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPWkFkdmVudHVyZS5wcm90bxoNT1pTdGFnZS5wcm90byJkCgtPWkFkdmVu",
            "dHVyZRIXCgVzdGFnZRgBIAEoCzIILk9aU3RhZ2USEwoLY2xlYXJfY291bnQY",
            "AiABKAUSEwoLcmVzZXRfY291bnQYAyABKAUSEgoKcmVzZXRfdGltZRgEIAEo",
            "A0IFqgICT3piBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.OZStageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.OZAdventure), global::Oz.OZAdventure.Parser, new[]{ "Stage", "ClearCount", "ResetCount", "ResetTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OZAdventure : pb::IMessage<OZAdventure>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OZAdventure> _parser = new pb::MessageParser<OZAdventure>(() => new OZAdventure());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OZAdventure> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.OZAdventureReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZAdventure() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZAdventure(OZAdventure other) : this() {
      stage_ = other.stage_ != null ? other.stage_.Clone() : null;
      clearCount_ = other.clearCount_;
      resetCount_ = other.resetCount_;
      resetTime_ = other.resetTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZAdventure Clone() {
      return new OZAdventure(this);
    }

    /// <summary>Field number for the "stage" field.</summary>
    public const int StageFieldNumber = 1;
    private global::Oz.OZStage stage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZStage Stage {
      get { return stage_; }
      set {
        stage_ = value;
      }
    }

    /// <summary>Field number for the "clear_count" field.</summary>
    public const int ClearCountFieldNumber = 2;
    private int clearCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClearCount {
      get { return clearCount_; }
      set {
        clearCount_ = value;
      }
    }

    /// <summary>Field number for the "reset_count" field.</summary>
    public const int ResetCountFieldNumber = 3;
    private int resetCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ResetCount {
      get { return resetCount_; }
      set {
        resetCount_ = value;
      }
    }

    /// <summary>Field number for the "reset_time" field.</summary>
    public const int ResetTimeFieldNumber = 4;
    private long resetTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResetTime {
      get { return resetTime_; }
      set {
        resetTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OZAdventure);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OZAdventure other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Stage, other.Stage)) return false;
      if (ClearCount != other.ClearCount) return false;
      if (ResetCount != other.ResetCount) return false;
      if (ResetTime != other.ResetTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (stage_ != null) hash ^= Stage.GetHashCode();
      if (ClearCount != 0) hash ^= ClearCount.GetHashCode();
      if (ResetCount != 0) hash ^= ResetCount.GetHashCode();
      if (ResetTime != 0L) hash ^= ResetTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (stage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Stage);
      }
      if (ClearCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClearCount);
      }
      if (ResetCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ResetCount);
      }
      if (ResetTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ResetTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (stage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Stage);
      }
      if (ClearCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ClearCount);
      }
      if (ResetCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ResetCount);
      }
      if (ResetTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ResetTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (stage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Stage);
      }
      if (ClearCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClearCount);
      }
      if (ResetCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResetCount);
      }
      if (ResetTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResetTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OZAdventure other) {
      if (other == null) {
        return;
      }
      if (other.stage_ != null) {
        if (stage_ == null) {
          Stage = new global::Oz.OZStage();
        }
        Stage.MergeFrom(other.Stage);
      }
      if (other.ClearCount != 0) {
        ClearCount = other.ClearCount;
      }
      if (other.ResetCount != 0) {
        ResetCount = other.ResetCount;
      }
      if (other.ResetTime != 0L) {
        ResetTime = other.ResetTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (stage_ == null) {
              Stage = new global::Oz.OZStage();
            }
            input.ReadMessage(Stage);
            break;
          }
          case 16: {
            ClearCount = input.ReadInt32();
            break;
          }
          case 24: {
            ResetCount = input.ReadInt32();
            break;
          }
          case 32: {
            ResetTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (stage_ == null) {
              Stage = new global::Oz.OZStage();
            }
            input.ReadMessage(Stage);
            break;
          }
          case 16: {
            ClearCount = input.ReadInt32();
            break;
          }
          case 24: {
            ResetCount = input.ReadInt32();
            break;
          }
          case 32: {
            ResetTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
