// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OZArena.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from OZArena.proto</summary>
  public static partial class OZArenaReflection {

    #region Descriptor
    /// <summary>File descriptor for OZArena.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OZArenaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1PWkFyZW5hLnByb3RvIogBCgdPWkFyZW5hEgoKAmlkGAEgASgJEg4KBnNl",
            "YXNvbhgCIAEoBRINCgVwb2ludBgDIAEoBRILCgN3aW4YBCABKAUSDAoEbG9z",
            "ZRgFIAEoBRIRCgl3aW5fc3RhY2sYBiABKAUSEQoJdXBkYXRlX2F0GAcgASgD",
            "EhEKCWNyZWF0ZV9hdBgIIAEoA0IFqgICT3piBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.OZArena), global::Oz.OZArena.Parser, new[]{ "Id", "Season", "Point", "Win", "Lose", "WinStack", "UpdateAt", "CreateAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OZArena : pb::IMessage<OZArena>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OZArena> _parser = new pb::MessageParser<OZArena>(() => new OZArena());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OZArena> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.OZArenaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZArena() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZArena(OZArena other) : this() {
      id_ = other.id_;
      season_ = other.season_;
      point_ = other.point_;
      win_ = other.win_;
      lose_ = other.lose_;
      winStack_ = other.winStack_;
      updateAt_ = other.updateAt_;
      createAt_ = other.createAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZArena Clone() {
      return new OZArena(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "season" field.</summary>
    public const int SeasonFieldNumber = 2;
    private int season_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Season {
      get { return season_; }
      set {
        season_ = value;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 3;
    private int point_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "win" field.</summary>
    public const int WinFieldNumber = 4;
    private int win_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Win {
      get { return win_; }
      set {
        win_ = value;
      }
    }

    /// <summary>Field number for the "lose" field.</summary>
    public const int LoseFieldNumber = 5;
    private int lose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Lose {
      get { return lose_; }
      set {
        lose_ = value;
      }
    }

    /// <summary>Field number for the "win_stack" field.</summary>
    public const int WinStackFieldNumber = 6;
    private int winStack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WinStack {
      get { return winStack_; }
      set {
        winStack_ = value;
      }
    }

    /// <summary>Field number for the "update_at" field.</summary>
    public const int UpdateAtFieldNumber = 7;
    private long updateAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UpdateAt {
      get { return updateAt_; }
      set {
        updateAt_ = value;
      }
    }

    /// <summary>Field number for the "create_at" field.</summary>
    public const int CreateAtFieldNumber = 8;
    private long createAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreateAt {
      get { return createAt_; }
      set {
        createAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OZArena);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OZArena other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Season != other.Season) return false;
      if (Point != other.Point) return false;
      if (Win != other.Win) return false;
      if (Lose != other.Lose) return false;
      if (WinStack != other.WinStack) return false;
      if (UpdateAt != other.UpdateAt) return false;
      if (CreateAt != other.CreateAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Season != 0) hash ^= Season.GetHashCode();
      if (Point != 0) hash ^= Point.GetHashCode();
      if (Win != 0) hash ^= Win.GetHashCode();
      if (Lose != 0) hash ^= Lose.GetHashCode();
      if (WinStack != 0) hash ^= WinStack.GetHashCode();
      if (UpdateAt != 0L) hash ^= UpdateAt.GetHashCode();
      if (CreateAt != 0L) hash ^= CreateAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Season != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Season);
      }
      if (Point != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Point);
      }
      if (Win != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Win);
      }
      if (Lose != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Lose);
      }
      if (WinStack != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WinStack);
      }
      if (UpdateAt != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(UpdateAt);
      }
      if (CreateAt != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(CreateAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Season != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Season);
      }
      if (Point != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Point);
      }
      if (Win != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Win);
      }
      if (Lose != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Lose);
      }
      if (WinStack != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WinStack);
      }
      if (UpdateAt != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(UpdateAt);
      }
      if (CreateAt != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(CreateAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Season != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Season);
      }
      if (Point != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Point);
      }
      if (Win != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Win);
      }
      if (Lose != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lose);
      }
      if (WinStack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WinStack);
      }
      if (UpdateAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UpdateAt);
      }
      if (CreateAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreateAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OZArena other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Season != 0) {
        Season = other.Season;
      }
      if (other.Point != 0) {
        Point = other.Point;
      }
      if (other.Win != 0) {
        Win = other.Win;
      }
      if (other.Lose != 0) {
        Lose = other.Lose;
      }
      if (other.WinStack != 0) {
        WinStack = other.WinStack;
      }
      if (other.UpdateAt != 0L) {
        UpdateAt = other.UpdateAt;
      }
      if (other.CreateAt != 0L) {
        CreateAt = other.CreateAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Season = input.ReadInt32();
            break;
          }
          case 24: {
            Point = input.ReadInt32();
            break;
          }
          case 32: {
            Win = input.ReadInt32();
            break;
          }
          case 40: {
            Lose = input.ReadInt32();
            break;
          }
          case 48: {
            WinStack = input.ReadInt32();
            break;
          }
          case 56: {
            UpdateAt = input.ReadInt64();
            break;
          }
          case 64: {
            CreateAt = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Season = input.ReadInt32();
            break;
          }
          case 24: {
            Point = input.ReadInt32();
            break;
          }
          case 32: {
            Win = input.ReadInt32();
            break;
          }
          case 40: {
            Lose = input.ReadInt32();
            break;
          }
          case 48: {
            WinStack = input.ReadInt32();
            break;
          }
          case 56: {
            UpdateAt = input.ReadInt64();
            break;
          }
          case 64: {
            CreateAt = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
