// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: OZReader.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Oz
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OZReader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"exp")]
        public long Exp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"login_time")]
        public long LoginTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"create_time")]
        public long CreateTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"profiles")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, OZProfile> Profiles { get; set; } = new global::System.Collections.Generic.Dictionary<int, OZProfile>();

        [global::ProtoBuf.ProtoMember(6, Name = @"high_ranks")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> HighRanks { get; set; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(7, Name = @"high_ruins")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, int> HighRuins { get; set; } = new global::System.Collections.Generic.Dictionary<string, int>();

        [global::ProtoBuf.ProtoMember(8, Name = @"high_stages")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, string> HighStages { get; set; } = new global::System.Collections.Generic.Dictionary<int, string>();

        [global::ProtoBuf.ProtoMember(9, Name = @"high_dungeons")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, int> HighDungeons { get; set; } = new global::System.Collections.Generic.Dictionary<string, int>();

        [global::ProtoBuf.ProtoMember(10, Name = @"high_total_war")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, int> HighTotalWars { get; set; } = new global::System.Collections.Generic.Dictionary<string, int>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
