// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OZResStage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from OZResStage.proto</summary>
  public static partial class OZResStageReflection {

    #region Descriptor
    /// <summary>File descriptor for OZResStage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OZResStageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBPWlJlc1N0YWdlLnByb3RvGg1PWkFyZW5hLnByb3RvGg1PWlJ1aW5zLnBy",
            "b3RvGg9PWkR1bmdlb24ucHJvdG8aEU9aQWR2ZW50dXJlLnByb3RvGhpPWlRv",
            "dGFsV2FyU3RhZ2VTdGF0ZS5wcm90bxoRU3RhZ2VSZXN1bHQucHJvdG8aE09a",
            "U3RhZ2VSZWNvcmQucHJvdG8iqQIKCk9aUmVzU3RhZ2USEQoJY2xvc2Vfc2Vj",
            "GAEgASgFEh0KC2NsZWFyX2FyZW5hGAIgASgLMgguT1pBcmVuYRIdCgtjbGVh",
            "cl9ydWlucxgDIAEoCzIILk9aUnVpbnMSIQoNY2xlYXJfZHVuZ2VvbhgEIAEo",
            "CzIKLk9aRHVuZ2VvbhIlCg9jbGVhcl9hZHZlbnR1cmUYBSABKAsyDC5PWkFk",
            "dmVudHVyZRI0ChV0b3RhbF93YXJfc3RhZ2Vfc3RhdGUYBiABKAsyFS5PWlRv",
            "dGFsV2FyU3RhZ2VTdGF0ZRIkCgxzdGFnZV9yZXN1bHQYByABKA4yDi5TdGFn",
            "ZVJlc3VsdC5UEiQKDHN0YWdlX3JlY29yZBgIIAEoCzIOLk9aU3RhZ2VSZWNv",
            "cmRCBaoCAk96YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.OZArenaReflection.Descriptor, global::Oz.OZRuinsReflection.Descriptor, global::Oz.OZDungeonReflection.Descriptor, global::Oz.OZAdventureReflection.Descriptor, global::Oz.OZTotalWarStageStateReflection.Descriptor, global::Oz.StageResultReflection.Descriptor, global::Oz.OZStageRecordReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.OZResStage), global::Oz.OZResStage.Parser, new[]{ "CloseSec", "ClearArena", "ClearRuins", "ClearDungeon", "ClearAdventure", "TotalWarStageState", "StageResult", "StageRecord" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OZResStage : pb::IMessage<OZResStage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OZResStage> _parser = new pb::MessageParser<OZResStage>(() => new OZResStage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OZResStage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.OZResStageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZResStage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZResStage(OZResStage other) : this() {
      closeSec_ = other.closeSec_;
      clearArena_ = other.clearArena_ != null ? other.clearArena_.Clone() : null;
      clearRuins_ = other.clearRuins_ != null ? other.clearRuins_.Clone() : null;
      clearDungeon_ = other.clearDungeon_ != null ? other.clearDungeon_.Clone() : null;
      clearAdventure_ = other.clearAdventure_ != null ? other.clearAdventure_.Clone() : null;
      totalWarStageState_ = other.totalWarStageState_ != null ? other.totalWarStageState_.Clone() : null;
      stageResult_ = other.stageResult_;
      stageRecord_ = other.stageRecord_ != null ? other.stageRecord_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZResStage Clone() {
      return new OZResStage(this);
    }

    /// <summary>Field number for the "close_sec" field.</summary>
    public const int CloseSecFieldNumber = 1;
    private int closeSec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CloseSec {
      get { return closeSec_; }
      set {
        closeSec_ = value;
      }
    }

    /// <summary>Field number for the "clear_arena" field.</summary>
    public const int ClearArenaFieldNumber = 2;
    private global::Oz.OZArena clearArena_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZArena ClearArena {
      get { return clearArena_; }
      set {
        clearArena_ = value;
      }
    }

    /// <summary>Field number for the "clear_ruins" field.</summary>
    public const int ClearRuinsFieldNumber = 3;
    private global::Oz.OZRuins clearRuins_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZRuins ClearRuins {
      get { return clearRuins_; }
      set {
        clearRuins_ = value;
      }
    }

    /// <summary>Field number for the "clear_dungeon" field.</summary>
    public const int ClearDungeonFieldNumber = 4;
    private global::Oz.OZDungeon clearDungeon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZDungeon ClearDungeon {
      get { return clearDungeon_; }
      set {
        clearDungeon_ = value;
      }
    }

    /// <summary>Field number for the "clear_adventure" field.</summary>
    public const int ClearAdventureFieldNumber = 5;
    private global::Oz.OZAdventure clearAdventure_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZAdventure ClearAdventure {
      get { return clearAdventure_; }
      set {
        clearAdventure_ = value;
      }
    }

    /// <summary>Field number for the "total_war_stage_state" field.</summary>
    public const int TotalWarStageStateFieldNumber = 6;
    private global::Oz.OZTotalWarStageState totalWarStageState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZTotalWarStageState TotalWarStageState {
      get { return totalWarStageState_; }
      set {
        totalWarStageState_ = value;
      }
    }

    /// <summary>Field number for the "stage_result" field.</summary>
    public const int StageResultFieldNumber = 7;
    private global::Oz.StageResult.Types.T stageResult_ = global::Oz.StageResult.Types.T.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.StageResult.Types.T StageResult {
      get { return stageResult_; }
      set {
        stageResult_ = value;
      }
    }

    /// <summary>Field number for the "stage_record" field.</summary>
    public const int StageRecordFieldNumber = 8;
    private global::Oz.OZStageRecord stageRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZStageRecord StageRecord {
      get { return stageRecord_; }
      set {
        stageRecord_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OZResStage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OZResStage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CloseSec != other.CloseSec) return false;
      if (!object.Equals(ClearArena, other.ClearArena)) return false;
      if (!object.Equals(ClearRuins, other.ClearRuins)) return false;
      if (!object.Equals(ClearDungeon, other.ClearDungeon)) return false;
      if (!object.Equals(ClearAdventure, other.ClearAdventure)) return false;
      if (!object.Equals(TotalWarStageState, other.TotalWarStageState)) return false;
      if (StageResult != other.StageResult) return false;
      if (!object.Equals(StageRecord, other.StageRecord)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CloseSec != 0) hash ^= CloseSec.GetHashCode();
      if (clearArena_ != null) hash ^= ClearArena.GetHashCode();
      if (clearRuins_ != null) hash ^= ClearRuins.GetHashCode();
      if (clearDungeon_ != null) hash ^= ClearDungeon.GetHashCode();
      if (clearAdventure_ != null) hash ^= ClearAdventure.GetHashCode();
      if (totalWarStageState_ != null) hash ^= TotalWarStageState.GetHashCode();
      if (StageResult != global::Oz.StageResult.Types.T.None) hash ^= StageResult.GetHashCode();
      if (stageRecord_ != null) hash ^= StageRecord.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CloseSec != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CloseSec);
      }
      if (clearArena_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClearArena);
      }
      if (clearRuins_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ClearRuins);
      }
      if (clearDungeon_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ClearDungeon);
      }
      if (clearAdventure_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ClearAdventure);
      }
      if (totalWarStageState_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TotalWarStageState);
      }
      if (StageResult != global::Oz.StageResult.Types.T.None) {
        output.WriteRawTag(56);
        output.WriteEnum((int) StageResult);
      }
      if (stageRecord_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(StageRecord);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CloseSec != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CloseSec);
      }
      if (clearArena_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ClearArena);
      }
      if (clearRuins_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ClearRuins);
      }
      if (clearDungeon_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ClearDungeon);
      }
      if (clearAdventure_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ClearAdventure);
      }
      if (totalWarStageState_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TotalWarStageState);
      }
      if (StageResult != global::Oz.StageResult.Types.T.None) {
        output.WriteRawTag(56);
        output.WriteEnum((int) StageResult);
      }
      if (stageRecord_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(StageRecord);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CloseSec != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CloseSec);
      }
      if (clearArena_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearArena);
      }
      if (clearRuins_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearRuins);
      }
      if (clearDungeon_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearDungeon);
      }
      if (clearAdventure_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearAdventure);
      }
      if (totalWarStageState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TotalWarStageState);
      }
      if (StageResult != global::Oz.StageResult.Types.T.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StageResult);
      }
      if (stageRecord_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StageRecord);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OZResStage other) {
      if (other == null) {
        return;
      }
      if (other.CloseSec != 0) {
        CloseSec = other.CloseSec;
      }
      if (other.clearArena_ != null) {
        if (clearArena_ == null) {
          ClearArena = new global::Oz.OZArena();
        }
        ClearArena.MergeFrom(other.ClearArena);
      }
      if (other.clearRuins_ != null) {
        if (clearRuins_ == null) {
          ClearRuins = new global::Oz.OZRuins();
        }
        ClearRuins.MergeFrom(other.ClearRuins);
      }
      if (other.clearDungeon_ != null) {
        if (clearDungeon_ == null) {
          ClearDungeon = new global::Oz.OZDungeon();
        }
        ClearDungeon.MergeFrom(other.ClearDungeon);
      }
      if (other.clearAdventure_ != null) {
        if (clearAdventure_ == null) {
          ClearAdventure = new global::Oz.OZAdventure();
        }
        ClearAdventure.MergeFrom(other.ClearAdventure);
      }
      if (other.totalWarStageState_ != null) {
        if (totalWarStageState_ == null) {
          TotalWarStageState = new global::Oz.OZTotalWarStageState();
        }
        TotalWarStageState.MergeFrom(other.TotalWarStageState);
      }
      if (other.StageResult != global::Oz.StageResult.Types.T.None) {
        StageResult = other.StageResult;
      }
      if (other.stageRecord_ != null) {
        if (stageRecord_ == null) {
          StageRecord = new global::Oz.OZStageRecord();
        }
        StageRecord.MergeFrom(other.StageRecord);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CloseSec = input.ReadInt32();
            break;
          }
          case 18: {
            if (clearArena_ == null) {
              ClearArena = new global::Oz.OZArena();
            }
            input.ReadMessage(ClearArena);
            break;
          }
          case 26: {
            if (clearRuins_ == null) {
              ClearRuins = new global::Oz.OZRuins();
            }
            input.ReadMessage(ClearRuins);
            break;
          }
          case 34: {
            if (clearDungeon_ == null) {
              ClearDungeon = new global::Oz.OZDungeon();
            }
            input.ReadMessage(ClearDungeon);
            break;
          }
          case 42: {
            if (clearAdventure_ == null) {
              ClearAdventure = new global::Oz.OZAdventure();
            }
            input.ReadMessage(ClearAdventure);
            break;
          }
          case 50: {
            if (totalWarStageState_ == null) {
              TotalWarStageState = new global::Oz.OZTotalWarStageState();
            }
            input.ReadMessage(TotalWarStageState);
            break;
          }
          case 56: {
            StageResult = (global::Oz.StageResult.Types.T) input.ReadEnum();
            break;
          }
          case 66: {
            if (stageRecord_ == null) {
              StageRecord = new global::Oz.OZStageRecord();
            }
            input.ReadMessage(StageRecord);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CloseSec = input.ReadInt32();
            break;
          }
          case 18: {
            if (clearArena_ == null) {
              ClearArena = new global::Oz.OZArena();
            }
            input.ReadMessage(ClearArena);
            break;
          }
          case 26: {
            if (clearRuins_ == null) {
              ClearRuins = new global::Oz.OZRuins();
            }
            input.ReadMessage(ClearRuins);
            break;
          }
          case 34: {
            if (clearDungeon_ == null) {
              ClearDungeon = new global::Oz.OZDungeon();
            }
            input.ReadMessage(ClearDungeon);
            break;
          }
          case 42: {
            if (clearAdventure_ == null) {
              ClearAdventure = new global::Oz.OZAdventure();
            }
            input.ReadMessage(ClearAdventure);
            break;
          }
          case 50: {
            if (totalWarStageState_ == null) {
              TotalWarStageState = new global::Oz.OZTotalWarStageState();
            }
            input.ReadMessage(TotalWarStageState);
            break;
          }
          case 56: {
            StageResult = (global::Oz.StageResult.Types.T) input.ReadEnum();
            break;
          }
          case 66: {
            if (stageRecord_ == null) {
              StageRecord = new global::Oz.OZStageRecord();
            }
            input.ReadMessage(StageRecord);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
