// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OZReader.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from OZReader.proto</summary>
  public static partial class OZReaderReflection {

    #region Descriptor
    /// <summary>File descriptor for OZReader.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OZReaderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5PWlJlYWRlci5wcm90bxoPT1pQcm9maWxlLnByb3RvIq0FCghPWlJlYWRl",
            "chILCgNleHAYASABKAMSDQoFbGV2ZWwYAiABKAUSEgoKbG9naW5fdGltZRgD",
            "IAEoAxITCgtjcmVhdGVfdGltZRgEIAEoAxIpCghwcm9maWxlcxgFIAMoCzIX",
            "Lk9aUmVhZGVyLlByb2ZpbGVzRW50cnkSLAoKaGlnaF9yYW5rcxgGIAMoCzIY",
            "Lk9aUmVhZGVyLkhpZ2hSYW5rc0VudHJ5EiwKCmhpZ2hfcnVpbnMYByADKAsy",
            "GC5PWlJlYWRlci5IaWdoUnVpbnNFbnRyeRIuCgtoaWdoX3N0YWdlcxgIIAMo",
            "CzIZLk9aUmVhZGVyLkhpZ2hTdGFnZXNFbnRyeRIyCg1oaWdoX2R1bmdlb25z",
            "GAkgAygLMhsuT1pSZWFkZXIuSGlnaER1bmdlb25zRW50cnkSMwoOaGlnaF90",
            "b3RhbF93YXIYCiADKAsyGy5PWlJlYWRlci5IaWdoVG90YWxXYXJFbnRyeRo7",
            "Cg1Qcm9maWxlc0VudHJ5EgsKA2tleRgBIAEoBRIZCgV2YWx1ZRgCIAEoCzIK",
            "Lk9aUHJvZmlsZToCOAEaMAoOSGlnaFJhbmtzRW50cnkSCwoDa2V5GAEgASgF",
            "Eg0KBXZhbHVlGAIgASgFOgI4ARowCg5IaWdoUnVpbnNFbnRyeRILCgNrZXkY",
            "ASABKAkSDQoFdmFsdWUYAiABKAU6AjgBGjEKD0hpZ2hTdGFnZXNFbnRyeRIL",
            "CgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAk6AjgBGjMKEUhpZ2hEdW5nZW9u",
            "c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoBToCOAEaMwoRSGln",
            "aFRvdGFsV2FyRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgFOgI4",
            "AUIFqgICT3piBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.OZProfileReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.OZReader), global::Oz.OZReader.Parser, new[]{ "Exp", "Level", "LoginTime", "CreateTime", "Profiles", "HighRanks", "HighRuins", "HighStages", "HighDungeons", "HighTotalWar" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OZReader : pb::IMessage<OZReader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OZReader> _parser = new pb::MessageParser<OZReader>(() => new OZReader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OZReader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.OZReaderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZReader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZReader(OZReader other) : this() {
      exp_ = other.exp_;
      level_ = other.level_;
      loginTime_ = other.loginTime_;
      createTime_ = other.createTime_;
      profiles_ = other.profiles_.Clone();
      highRanks_ = other.highRanks_.Clone();
      highRuins_ = other.highRuins_.Clone();
      highStages_ = other.highStages_.Clone();
      highDungeons_ = other.highDungeons_.Clone();
      highTotalWar_ = other.highTotalWar_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZReader Clone() {
      return new OZReader(this);
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 1;
    private long exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "login_time" field.</summary>
    public const int LoginTimeFieldNumber = 3;
    private long loginTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LoginTime {
      get { return loginTime_; }
      set {
        loginTime_ = value;
      }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 4;
    private long createTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "profiles" field.</summary>
    public const int ProfilesFieldNumber = 5;
    private static readonly pbc::MapField<int, global::Oz.OZProfile>.Codec _map_profiles_codec
        = new pbc::MapField<int, global::Oz.OZProfile>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Oz.OZProfile.Parser), 42);
    private readonly pbc::MapField<int, global::Oz.OZProfile> profiles_ = new pbc::MapField<int, global::Oz.OZProfile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Oz.OZProfile> Profiles {
      get { return profiles_; }
    }

    /// <summary>Field number for the "high_ranks" field.</summary>
    public const int HighRanksFieldNumber = 6;
    private static readonly pbc::MapField<int, int>.Codec _map_highRanks_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 50);
    private readonly pbc::MapField<int, int> highRanks_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> HighRanks {
      get { return highRanks_; }
    }

    /// <summary>Field number for the "high_ruins" field.</summary>
    public const int HighRuinsFieldNumber = 7;
    private static readonly pbc::MapField<string, int>.Codec _map_highRuins_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 58);
    private readonly pbc::MapField<string, int> highRuins_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> HighRuins {
      get { return highRuins_; }
    }

    /// <summary>Field number for the "high_stages" field.</summary>
    public const int HighStagesFieldNumber = 8;
    private static readonly pbc::MapField<int, string>.Codec _map_highStages_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 66);
    private readonly pbc::MapField<int, string> highStages_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> HighStages {
      get { return highStages_; }
    }

    /// <summary>Field number for the "high_dungeons" field.</summary>
    public const int HighDungeonsFieldNumber = 9;
    private static readonly pbc::MapField<string, int>.Codec _map_highDungeons_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 74);
    private readonly pbc::MapField<string, int> highDungeons_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> HighDungeons {
      get { return highDungeons_; }
    }

    /// <summary>Field number for the "high_total_war" field.</summary>
    public const int HighTotalWarFieldNumber = 10;
    private static readonly pbc::MapField<string, int>.Codec _map_highTotalWar_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 82);
    private readonly pbc::MapField<string, int> highTotalWar_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> HighTotalWar {
      get { return highTotalWar_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OZReader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OZReader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Exp != other.Exp) return false;
      if (Level != other.Level) return false;
      if (LoginTime != other.LoginTime) return false;
      if (CreateTime != other.CreateTime) return false;
      if (!Profiles.Equals(other.Profiles)) return false;
      if (!HighRanks.Equals(other.HighRanks)) return false;
      if (!HighRuins.Equals(other.HighRuins)) return false;
      if (!HighStages.Equals(other.HighStages)) return false;
      if (!HighDungeons.Equals(other.HighDungeons)) return false;
      if (!HighTotalWar.Equals(other.HighTotalWar)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Exp != 0L) hash ^= Exp.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (LoginTime != 0L) hash ^= LoginTime.GetHashCode();
      if (CreateTime != 0L) hash ^= CreateTime.GetHashCode();
      hash ^= Profiles.GetHashCode();
      hash ^= HighRanks.GetHashCode();
      hash ^= HighRuins.GetHashCode();
      hash ^= HighStages.GetHashCode();
      hash ^= HighDungeons.GetHashCode();
      hash ^= HighTotalWar.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Exp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Exp);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (LoginTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(LoginTime);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CreateTime);
      }
      profiles_.WriteTo(output, _map_profiles_codec);
      highRanks_.WriteTo(output, _map_highRanks_codec);
      highRuins_.WriteTo(output, _map_highRuins_codec);
      highStages_.WriteTo(output, _map_highStages_codec);
      highDungeons_.WriteTo(output, _map_highDungeons_codec);
      highTotalWar_.WriteTo(output, _map_highTotalWar_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Exp != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Exp);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (LoginTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(LoginTime);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CreateTime);
      }
      profiles_.WriteTo(ref output, _map_profiles_codec);
      highRanks_.WriteTo(ref output, _map_highRanks_codec);
      highRuins_.WriteTo(ref output, _map_highRuins_codec);
      highStages_.WriteTo(ref output, _map_highStages_codec);
      highDungeons_.WriteTo(ref output, _map_highDungeons_codec);
      highTotalWar_.WriteTo(ref output, _map_highTotalWar_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Exp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (LoginTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LoginTime);
      }
      if (CreateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreateTime);
      }
      size += profiles_.CalculateSize(_map_profiles_codec);
      size += highRanks_.CalculateSize(_map_highRanks_codec);
      size += highRuins_.CalculateSize(_map_highRuins_codec);
      size += highStages_.CalculateSize(_map_highStages_codec);
      size += highDungeons_.CalculateSize(_map_highDungeons_codec);
      size += highTotalWar_.CalculateSize(_map_highTotalWar_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OZReader other) {
      if (other == null) {
        return;
      }
      if (other.Exp != 0L) {
        Exp = other.Exp;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.LoginTime != 0L) {
        LoginTime = other.LoginTime;
      }
      if (other.CreateTime != 0L) {
        CreateTime = other.CreateTime;
      }
      profiles_.MergeFrom(other.profiles_);
      highRanks_.MergeFrom(other.highRanks_);
      highRuins_.MergeFrom(other.highRuins_);
      highStages_.MergeFrom(other.highStages_);
      highDungeons_.MergeFrom(other.highDungeons_);
      highTotalWar_.MergeFrom(other.highTotalWar_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Exp = input.ReadInt64();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            LoginTime = input.ReadInt64();
            break;
          }
          case 32: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 42: {
            profiles_.AddEntriesFrom(input, _map_profiles_codec);
            break;
          }
          case 50: {
            highRanks_.AddEntriesFrom(input, _map_highRanks_codec);
            break;
          }
          case 58: {
            highRuins_.AddEntriesFrom(input, _map_highRuins_codec);
            break;
          }
          case 66: {
            highStages_.AddEntriesFrom(input, _map_highStages_codec);
            break;
          }
          case 74: {
            highDungeons_.AddEntriesFrom(input, _map_highDungeons_codec);
            break;
          }
          case 82: {
            highTotalWar_.AddEntriesFrom(input, _map_highTotalWar_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Exp = input.ReadInt64();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            LoginTime = input.ReadInt64();
            break;
          }
          case 32: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 42: {
            profiles_.AddEntriesFrom(ref input, _map_profiles_codec);
            break;
          }
          case 50: {
            highRanks_.AddEntriesFrom(ref input, _map_highRanks_codec);
            break;
          }
          case 58: {
            highRuins_.AddEntriesFrom(ref input, _map_highRuins_codec);
            break;
          }
          case 66: {
            highStages_.AddEntriesFrom(ref input, _map_highStages_codec);
            break;
          }
          case 74: {
            highDungeons_.AddEntriesFrom(ref input, _map_highDungeons_codec);
            break;
          }
          case 82: {
            highTotalWar_.AddEntriesFrom(ref input, _map_highTotalWar_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
