// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: OZResStage.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Oz
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OZResStage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"close_sec")]
        public int CloseSec { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clear_arena")]
        public OZArena ClearArena { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clear_ruins")]
        public OZRuins ClearRuins { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clear_dungeon")]
        public OZDungeon ClearDungeon { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"clear_adventure")]
        public OZAdventure ClearAdventure { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"total_war_stage_state")]
        public OZTotalWarStageState TotalWarStageState { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"stage_result")]
        public StageResult.T StageResult { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"stage_record")]
        public OZStageRecord StageRecord { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
