// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OZTotalWarStageState.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from OZTotalWarStageState.proto</summary>
  public static partial class OZTotalWarStageStateReflection {

    #region Descriptor
    /// <summary>File descriptor for OZTotalWarStageState.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OZTotalWarStageStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpPWlRvdGFsV2FyU3RhZ2VTdGF0ZS5wcm90bxoNT1pTdGFnZS5wcm90bxoV",
            "T1pUb3RhbFdhclBhcnR5LnByb3RvIuEBChRPWlRvdGFsV2FyU3RhZ2VTdGF0",
            "ZRIXCgVzdGFnZRgBIAEoCzIILk9aU3RhZ2USEgoKc2Vhc29uX251bRgCIAEo",
            "BRIVCg1pc19zaW11bGF0aW9uGAMgASgIEg0KBXBvaW50GAQgASgDEhIKCmVu",
            "dGVyX3RpbWUYBSABKAMSEwoLZXhwaXJlX3RpbWUYBiABKAMSEwoLZW50cnlf",
            "Y291bnQYByABKAUSDwoHYm9zc19ocBgIIAEoAxInCg1lbnRyeV9wYXJ0aWVz",
            "GAkgAygLMhAuT1pUb3RhbFdhclBhcnR5QgWqAgJPemIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.OZStageReflection.Descriptor, global::Oz.OZTotalWarPartyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.OZTotalWarStageState), global::Oz.OZTotalWarStageState.Parser, new[]{ "Stage", "SeasonNum", "IsSimulation", "Point", "EnterTime", "ExpireTime", "EntryCount", "BossHp", "EntryParties" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OZTotalWarStageState : pb::IMessage<OZTotalWarStageState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OZTotalWarStageState> _parser = new pb::MessageParser<OZTotalWarStageState>(() => new OZTotalWarStageState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OZTotalWarStageState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.OZTotalWarStageStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZTotalWarStageState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZTotalWarStageState(OZTotalWarStageState other) : this() {
      stage_ = other.stage_ != null ? other.stage_.Clone() : null;
      seasonNum_ = other.seasonNum_;
      isSimulation_ = other.isSimulation_;
      point_ = other.point_;
      enterTime_ = other.enterTime_;
      expireTime_ = other.expireTime_;
      entryCount_ = other.entryCount_;
      bossHp_ = other.bossHp_;
      entryParties_ = other.entryParties_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OZTotalWarStageState Clone() {
      return new OZTotalWarStageState(this);
    }

    /// <summary>Field number for the "stage" field.</summary>
    public const int StageFieldNumber = 1;
    private global::Oz.OZStage stage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.OZStage Stage {
      get { return stage_; }
      set {
        stage_ = value;
      }
    }

    /// <summary>Field number for the "season_num" field.</summary>
    public const int SeasonNumFieldNumber = 2;
    private int seasonNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonNum {
      get { return seasonNum_; }
      set {
        seasonNum_ = value;
      }
    }

    /// <summary>Field number for the "is_simulation" field.</summary>
    public const int IsSimulationFieldNumber = 3;
    private bool isSimulation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSimulation {
      get { return isSimulation_; }
      set {
        isSimulation_ = value;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 4;
    private long point_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "enter_time" field.</summary>
    public const int EnterTimeFieldNumber = 5;
    private long enterTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EnterTime {
      get { return enterTime_; }
      set {
        enterTime_ = value;
      }
    }

    /// <summary>Field number for the "expire_time" field.</summary>
    public const int ExpireTimeFieldNumber = 6;
    private long expireTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpireTime {
      get { return expireTime_; }
      set {
        expireTime_ = value;
      }
    }

    /// <summary>Field number for the "entry_count" field.</summary>
    public const int EntryCountFieldNumber = 7;
    private int entryCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EntryCount {
      get { return entryCount_; }
      set {
        entryCount_ = value;
      }
    }

    /// <summary>Field number for the "boss_hp" field.</summary>
    public const int BossHpFieldNumber = 8;
    private long bossHp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BossHp {
      get { return bossHp_; }
      set {
        bossHp_ = value;
      }
    }

    /// <summary>Field number for the "entry_parties" field.</summary>
    public const int EntryPartiesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Oz.OZTotalWarParty> _repeated_entryParties_codec
        = pb::FieldCodec.ForMessage(74, global::Oz.OZTotalWarParty.Parser);
    private readonly pbc::RepeatedField<global::Oz.OZTotalWarParty> entryParties_ = new pbc::RepeatedField<global::Oz.OZTotalWarParty>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oz.OZTotalWarParty> EntryParties {
      get { return entryParties_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OZTotalWarStageState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OZTotalWarStageState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Stage, other.Stage)) return false;
      if (SeasonNum != other.SeasonNum) return false;
      if (IsSimulation != other.IsSimulation) return false;
      if (Point != other.Point) return false;
      if (EnterTime != other.EnterTime) return false;
      if (ExpireTime != other.ExpireTime) return false;
      if (EntryCount != other.EntryCount) return false;
      if (BossHp != other.BossHp) return false;
      if(!entryParties_.Equals(other.entryParties_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (stage_ != null) hash ^= Stage.GetHashCode();
      if (SeasonNum != 0) hash ^= SeasonNum.GetHashCode();
      if (IsSimulation != false) hash ^= IsSimulation.GetHashCode();
      if (Point != 0L) hash ^= Point.GetHashCode();
      if (EnterTime != 0L) hash ^= EnterTime.GetHashCode();
      if (ExpireTime != 0L) hash ^= ExpireTime.GetHashCode();
      if (EntryCount != 0) hash ^= EntryCount.GetHashCode();
      if (BossHp != 0L) hash ^= BossHp.GetHashCode();
      hash ^= entryParties_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (stage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Stage);
      }
      if (SeasonNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SeasonNum);
      }
      if (IsSimulation != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsSimulation);
      }
      if (Point != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Point);
      }
      if (EnterTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(EnterTime);
      }
      if (ExpireTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ExpireTime);
      }
      if (EntryCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(EntryCount);
      }
      if (BossHp != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(BossHp);
      }
      entryParties_.WriteTo(output, _repeated_entryParties_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (stage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Stage);
      }
      if (SeasonNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SeasonNum);
      }
      if (IsSimulation != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsSimulation);
      }
      if (Point != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Point);
      }
      if (EnterTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(EnterTime);
      }
      if (ExpireTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ExpireTime);
      }
      if (EntryCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(EntryCount);
      }
      if (BossHp != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(BossHp);
      }
      entryParties_.WriteTo(ref output, _repeated_entryParties_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (stage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Stage);
      }
      if (SeasonNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonNum);
      }
      if (IsSimulation != false) {
        size += 1 + 1;
      }
      if (Point != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Point);
      }
      if (EnterTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EnterTime);
      }
      if (ExpireTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ExpireTime);
      }
      if (EntryCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntryCount);
      }
      if (BossHp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BossHp);
      }
      size += entryParties_.CalculateSize(_repeated_entryParties_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OZTotalWarStageState other) {
      if (other == null) {
        return;
      }
      if (other.stage_ != null) {
        if (stage_ == null) {
          Stage = new global::Oz.OZStage();
        }
        Stage.MergeFrom(other.Stage);
      }
      if (other.SeasonNum != 0) {
        SeasonNum = other.SeasonNum;
      }
      if (other.IsSimulation != false) {
        IsSimulation = other.IsSimulation;
      }
      if (other.Point != 0L) {
        Point = other.Point;
      }
      if (other.EnterTime != 0L) {
        EnterTime = other.EnterTime;
      }
      if (other.ExpireTime != 0L) {
        ExpireTime = other.ExpireTime;
      }
      if (other.EntryCount != 0) {
        EntryCount = other.EntryCount;
      }
      if (other.BossHp != 0L) {
        BossHp = other.BossHp;
      }
      entryParties_.Add(other.entryParties_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (stage_ == null) {
              Stage = new global::Oz.OZStage();
            }
            input.ReadMessage(Stage);
            break;
          }
          case 16: {
            SeasonNum = input.ReadInt32();
            break;
          }
          case 24: {
            IsSimulation = input.ReadBool();
            break;
          }
          case 32: {
            Point = input.ReadInt64();
            break;
          }
          case 40: {
            EnterTime = input.ReadInt64();
            break;
          }
          case 48: {
            ExpireTime = input.ReadInt64();
            break;
          }
          case 56: {
            EntryCount = input.ReadInt32();
            break;
          }
          case 64: {
            BossHp = input.ReadInt64();
            break;
          }
          case 74: {
            entryParties_.AddEntriesFrom(input, _repeated_entryParties_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (stage_ == null) {
              Stage = new global::Oz.OZStage();
            }
            input.ReadMessage(Stage);
            break;
          }
          case 16: {
            SeasonNum = input.ReadInt32();
            break;
          }
          case 24: {
            IsSimulation = input.ReadBool();
            break;
          }
          case 32: {
            Point = input.ReadInt64();
            break;
          }
          case 40: {
            EnterTime = input.ReadInt64();
            break;
          }
          case 48: {
            ExpireTime = input.ReadInt64();
            break;
          }
          case 56: {
            EntryCount = input.ReadInt32();
            break;
          }
          case 64: {
            BossHp = input.ReadInt64();
            break;
          }
          case 74: {
            entryParties_.AddEntriesFrom(ref input, _repeated_entryParties_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
