// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SocketBlockReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from SocketBlockReq.proto</summary>
  public static partial class SocketBlockReqReflection {

    #region Descriptor
    /// <summary>File descriptor for SocketBlockReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SocketBlockReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRTb2NrZXRCbG9ja1JlcS5wcm90bxoRSHliZUJsb2NrSWQucHJvdG8aF0h5",
            "YmVCbG9ja1JlYXNvbklkLnByb3RvGhFPWkJsb2NrTWV0YS5wcm90byKoAQoO",
            "U29ja2V0QmxvY2tSZXESEAoIdXNlcl9pZHMYASADKAkSGQoRYmxvY2tfZXhw",
            "aXJlX3RpbWUYAiABKAMSIAoIYmxvY2tfaWQYAyABKA4yDi5IeWJlQmxvY2tJ",
            "ZC5UEicKCXJlYXNvbl9pZBgEIAEoDjIULkh5YmVCbG9ja1JlYXNvbklkLlQS",
            "HgoIbWV0YWRhdGEYBSADKAsyDC5PWkJsb2NrTWV0YUIFqgICT3piBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oz.HybeBlockIdReflection.Descriptor, global::Oz.HybeBlockReasonIdReflection.Descriptor, global::Oz.OZBlockMetaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oz.SocketBlockReq), global::Oz.SocketBlockReq.Parser, new[]{ "UserIds", "BlockExpireTime", "BlockId", "ReasonId", "Metadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SocketBlockReq : pb::IMessage<SocketBlockReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SocketBlockReq> _parser = new pb::MessageParser<SocketBlockReq>(() => new SocketBlockReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SocketBlockReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oz.SocketBlockReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SocketBlockReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SocketBlockReq(SocketBlockReq other) : this() {
      userIds_ = other.userIds_.Clone();
      blockExpireTime_ = other.blockExpireTime_;
      blockId_ = other.blockId_;
      reasonId_ = other.reasonId_;
      metadata_ = other.metadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SocketBlockReq Clone() {
      return new SocketBlockReq(this);
    }

    /// <summary>Field number for the "user_ids" field.</summary>
    public const int UserIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_userIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> userIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> UserIds {
      get { return userIds_; }
    }

    /// <summary>Field number for the "block_expire_time" field.</summary>
    public const int BlockExpireTimeFieldNumber = 2;
    private long blockExpireTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BlockExpireTime {
      get { return blockExpireTime_; }
      set {
        blockExpireTime_ = value;
      }
    }

    /// <summary>Field number for the "block_id" field.</summary>
    public const int BlockIdFieldNumber = 3;
    private global::Oz.HybeBlockId.Types.T blockId_ = global::Oz.HybeBlockId.Types.T.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.HybeBlockId.Types.T BlockId {
      get { return blockId_; }
      set {
        blockId_ = value;
      }
    }

    /// <summary>Field number for the "reason_id" field.</summary>
    public const int ReasonIdFieldNumber = 4;
    private global::Oz.HybeBlockReasonId.Types.T reasonId_ = global::Oz.HybeBlockReasonId.Types.T.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oz.HybeBlockReasonId.Types.T ReasonId {
      get { return reasonId_; }
      set {
        reasonId_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Oz.OZBlockMeta> _repeated_metadata_codec
        = pb::FieldCodec.ForMessage(42, global::Oz.OZBlockMeta.Parser);
    private readonly pbc::RepeatedField<global::Oz.OZBlockMeta> metadata_ = new pbc::RepeatedField<global::Oz.OZBlockMeta>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oz.OZBlockMeta> Metadata {
      get { return metadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SocketBlockReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SocketBlockReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!userIds_.Equals(other.userIds_)) return false;
      if (BlockExpireTime != other.BlockExpireTime) return false;
      if (BlockId != other.BlockId) return false;
      if (ReasonId != other.ReasonId) return false;
      if(!metadata_.Equals(other.metadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= userIds_.GetHashCode();
      if (BlockExpireTime != 0L) hash ^= BlockExpireTime.GetHashCode();
      if (BlockId != global::Oz.HybeBlockId.Types.T.None) hash ^= BlockId.GetHashCode();
      if (ReasonId != global::Oz.HybeBlockReasonId.Types.T.None) hash ^= ReasonId.GetHashCode();
      hash ^= metadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      userIds_.WriteTo(output, _repeated_userIds_codec);
      if (BlockExpireTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(BlockExpireTime);
      }
      if (BlockId != global::Oz.HybeBlockId.Types.T.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) BlockId);
      }
      if (ReasonId != global::Oz.HybeBlockReasonId.Types.T.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ReasonId);
      }
      metadata_.WriteTo(output, _repeated_metadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      userIds_.WriteTo(ref output, _repeated_userIds_codec);
      if (BlockExpireTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(BlockExpireTime);
      }
      if (BlockId != global::Oz.HybeBlockId.Types.T.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) BlockId);
      }
      if (ReasonId != global::Oz.HybeBlockReasonId.Types.T.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ReasonId);
      }
      metadata_.WriteTo(ref output, _repeated_metadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += userIds_.CalculateSize(_repeated_userIds_codec);
      if (BlockExpireTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BlockExpireTime);
      }
      if (BlockId != global::Oz.HybeBlockId.Types.T.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BlockId);
      }
      if (ReasonId != global::Oz.HybeBlockReasonId.Types.T.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReasonId);
      }
      size += metadata_.CalculateSize(_repeated_metadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SocketBlockReq other) {
      if (other == null) {
        return;
      }
      userIds_.Add(other.userIds_);
      if (other.BlockExpireTime != 0L) {
        BlockExpireTime = other.BlockExpireTime;
      }
      if (other.BlockId != global::Oz.HybeBlockId.Types.T.None) {
        BlockId = other.BlockId;
      }
      if (other.ReasonId != global::Oz.HybeBlockReasonId.Types.T.None) {
        ReasonId = other.ReasonId;
      }
      metadata_.Add(other.metadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            userIds_.AddEntriesFrom(input, _repeated_userIds_codec);
            break;
          }
          case 16: {
            BlockExpireTime = input.ReadInt64();
            break;
          }
          case 24: {
            BlockId = (global::Oz.HybeBlockId.Types.T) input.ReadEnum();
            break;
          }
          case 32: {
            ReasonId = (global::Oz.HybeBlockReasonId.Types.T) input.ReadEnum();
            break;
          }
          case 42: {
            metadata_.AddEntriesFrom(input, _repeated_metadata_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            userIds_.AddEntriesFrom(ref input, _repeated_userIds_codec);
            break;
          }
          case 16: {
            BlockExpireTime = input.ReadInt64();
            break;
          }
          case 24: {
            BlockId = (global::Oz.HybeBlockId.Types.T) input.ReadEnum();
            break;
          }
          case 32: {
            ReasonId = (global::Oz.HybeBlockReasonId.Types.T) input.ReadEnum();
            break;
          }
          case 42: {
            metadata_.AddEntriesFrom(ref input, _repeated_metadata_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
