// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TotalWarRankTierType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oz {

  /// <summary>Holder for reflection information generated from TotalWarRankTierType.proto</summary>
  public static partial class TotalWarRankTierTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for TotalWarRankTierType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TotalWarRankTierTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpUb3RhbFdhclJhbmtUaWVyVHlwZS5wcm90byrXAQoUVG90YWxXYXJSYW5r",
            "VGllclR5cGUSHQoZVG90YWxXYXJSYW5rVGllclR5cGVfTm9uZRAAEiEKHVRv",
            "dGFsV2FyUmFua1RpZXJUeXBlX1BsYXRpbnVtEAESHQoZVG90YWxXYXJSYW5r",
            "VGllclR5cGVfR29sZBACEh8KG1RvdGFsV2FyUmFua1RpZXJUeXBlX1NpbHZl",
            "chADEh8KG1RvdGFsV2FyUmFua1RpZXJUeXBlX0Jyb256ZRAEEhwKGFRvdGFs",
            "V2FyUmFua1RpZXJUeXBlX01BWBAFQgWqAgJPemIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Oz.TotalWarRankTierType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TotalWarRankTierType {
    [pbr::OriginalName("TotalWarRankTierType_None")] None = 0,
    [pbr::OriginalName("TotalWarRankTierType_Platinum")] Platinum = 1,
    [pbr::OriginalName("TotalWarRankTierType_Gold")] Gold = 2,
    [pbr::OriginalName("TotalWarRankTierType_Silver")] Silver = 3,
    [pbr::OriginalName("TotalWarRankTierType_Bronze")] Bronze = 4,
    [pbr::OriginalName("TotalWarRankTierType_MAX")] Max = 5,
  }

  #endregion

}

#endregion Designer generated code
