// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: TotalWarDifficultType.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Oz
{

    [global::ProtoBuf.ProtoContract()]
    public enum TotalWarDifficultType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_None")]
        TotalWarDifficultTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_Normal")]
        TotalWarDifficultTypeNormal = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_Hard")]
        TotalWarDifficultTypeHard = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_Expert")]
        TotalWarDifficultTypeExpert = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_Master")]
        TotalWarDifficultTypeMaster = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_Torment")]
        TotalWarDifficultTypeTorment = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"TotalWarDifficultType_MAX")]
        TotalWarDifficultTypeMAX = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
